output "ecs_public_ip" {
  value       = huaweicloud_vpc_eip.eip.address
  description = "Public IP of the devbox ECS"
}

output "ecs_private_ip" {
  value       = huaweicloud_compute_instance.ecs.network[0].fixed_ip_v4
  description = "Private IP of the devbox ECS"
}

output "ecs_private_key" {
  value       = tls_private_key.ssh_key.private_key_pem
  sensitive   = true
  description = "Private SSH key for the ECS (generated by Terraform)"
}

output "csms_secret_name" {
  value       = huaweicloud_csms_secret.private_key.name
  description = "CSMS secret name where the private key is stored (DEW)"
}

output "keypair_name" {
  value       = huaweicloud_compute_keypair.keypair.name
  description = "Key pair name registered in Huawei Cloud"
}

output "devbox_url" {
  value       = "https://${var.devbox_domain}"
  description = "URL del escritorio, una vez que el A record resuelva y Caddy emita el certificado"
}
